dist: bionic
sudo: required
language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libsdl2-dev
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake .. -DWITH_YM2151=ON
        - make
    - os: osx
      osx_image: xcode11
      addons:
        homebrew:
          packages:
            - cmake
            - sdl2 
      script:
        - mkdir build && cd build
        - cmake .. -DWITH_YM2151=ON
        - make
