image:
  - Visual Studio 2019

clone_depth: 1

cache:
  - C:\Users\appveyor\.conan -> conanfile.py
  - C:\.conan -> conanfile.py

environment:
  PYTHON: "C:\\Python36-x64"
  matrix:
    - ARCH: x86
    - ARCH: x86_64

configuration:
  - Release

matrix:
  fast_finish: false

init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - cmake --version
  - msbuild /version

install:
  - python -m pip install conan
  - conan user
  - conan remote add -f bincrafters https://api.bintray.com/conan/bincrafters/public-conan

build_script:
  - git clone https://github.com/commanderx16/x16-docs.git --depth 1
  - git clone https://github.com/commanderx16/x16-rom.git --depth 1
  - mkdir build && cd build
  - conan install .. -s arch=%ARCH% -s build_type=%CONFIGURATION% -o x16docs_path=../x16-docs -o x16rom_path=../x16-rom
  - conan build ..

after_build:
  - cpack -C %CONFIGURATION% -G TXZ

artifacts:
  - path: build/x16emu-Windows-$(ARCH).tar.xz
